version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_main
    hostname: db
    environment:
      POSTGRES_PASSWORD: dbPass
      POSTGRES_USER: dbUser
      POSTGRES_DB: docker-db
    volumes:
      - pgdata:/pgdata
    ports:
      - "5432:5432"
    networks:
      - wiki
  dbTest:
    image: postgres
    container_name: dbTest
    hostname: dbTest
    environment:
      POSTGRES_PASSWORD: dbTestPass
      POSTGRES_USER: dbTestUser
    ports:
      - "5400:5432"
    networks:
      - wiki
  node_app:
    container_name: node_app
    hostname: node_app
    build: .
    depends_on:
      - db
      - db_test
    restart: on-failure
    command: bash -c "npm run migrateUp && npm run start"
    environment:
      DB_HOST: db
      DB_USER: dbUser
      DB_PASS: dbPass
      DB_TEST_HOST: localhost
      TEST_USER: dbTestUser
      TEST_PASS: dbTestPass
      NODE_ENV: development
      DEV: docker-db
    env_file: .env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - wiki
volumes:
  pgdata:
networks:
  wiki: